### ISSUE TITLE
Auth via connect button?

### ISSUE THREAD

**Issue by dcts** [radixdlt/connect-button#81]
I am not sure if this is feasible, but is there any way to let users use the connect button to auth (basically prooving to our backend server that the user does own the private key to that radix account)? Kind of like "login with google" but "login with radix wallet". 

Ideally I need a service where users can signup / login via wallet app instead of creating a new account (with email  or login with google / facebook or similar).

A use case might be: I have a centralized service that lets you track radix wallet's and sends emails whenever a new transaction on one of the watched addresses is submitted. Ideally users do not need to signup with email but can signup by connecting their radix wallet only. Additionally I want to give a discount for all users that did their first transaction before 2024. 

edit: I think this can be done using ROLA. (https://docs.radixdlt.com/docs/rola-radix-off-ledger-auth)

**Comment by dawidsowardx** [comment]
Yes, ROLA is the answer. If in doubt, please reach out to us and other developers through [discord](http://discord.gg/radixdlt)
